sudo : required
services : 
  - docker

before_install :
  - docker build -t elastic_volhard/docker-react2 -f Dockerfile.dev .
  

script :
  - docker run elastic_volhard/docker-react2 npm run test -- --coverage