sudo : required
services : 
  - docker

before_install :
  - docker build -t elastic_volhard/docker-react2 -f Dockerfile.dev .
  

script :
  - docker run elastic_volhard/docker-react2 npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "th"
  app : "docker"
  env : "name-project-aws"
  bucket_name : "docker"
on :
  branch : main
access_key_id : $AWS_ACCESS_KEY
secret_access_key :
  secure : "$AWS_SECRET_KEY"